gen-proto:
	protoc protos/*.proto --plugin=protoc-gen-go=$(go env GOPATH)/bin/protoc-gen-go.exe --go_out=.

gen-grpc:
	protoc protos/user_service.proto --plugin=protoc-gen-go-grpc=$(go env GOPATH)/bin/protoc-gen-go-grpc.exe --go-grpc_out=.